version: '3'
services:
  chatfe:
    build: ./fe
    container_name: nginx
    restart: always
    ports:
      - 80:80

  chatbe:
    restart: always
    build: ./api
    ports:
      - 8080:8080
    expose:
      - "8080"